"""create comparisons table

Revision ID: 276248ecd392
Revises: dab0ad230869
Create Date: 2026-04-24 17:08:30.142935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276248ecd392'
down_revision = 'dab0ad230869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('sector_avg_pe', sa.Float(), nullable=True),
    sa.Column('sector_avg_pb', sa.Float(), nullable=True),
    sa.Column('sector_avg_roe', sa.Float(), nullable=True),
    sa.Column('sector_avg_roa', sa.Float(), nullable=True),
    sa.Column('sector_avg_debt_to_equity', sa.Float(), nullable=True),
    sa.Column('sector_avg_profit_margin', sa.Float(), nullable=True),
    sa.Column('sector_avg_dividend_yield', sa.Float(), nullable=True),
    sa.Column('pe_rank', sa.Integer(), nullable=True),
    sa.Column('pb_rank', sa.Integer(), nullable=True),
    sa.Column('roe_rank', sa.Integer(), nullable=True),
    sa.Column('roa_rank', sa.Integer(), nullable=True),
    sa.Column('debt_to_equity_rank', sa.Integer(), nullable=True),
    sa.Column('profit_margin_rank', sa.Integer(), nullable=True),
    sa.Column('dividend_yield_rank', sa.Integer(), nullable=True),
    sa.Column('peer_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparisons')
    # ### end Alembic commands ###
