"""rename 3 columns: total_borrowings, cash_and_equivalents, shares_outstanding

Revision ID: dab0ad230869
Revises: a5dc4d49ccce
Create Date: 2026-04-01 00:03:41.042155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab0ad230869'
down_revision = 'a5dc4d49ccce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_borrowings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cash_and_equivalents', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shares_outstanding', sa.Float(), nullable=True))
        batch_op.drop_column('operating_cash_flow')
        batch_op.drop_column('total_liabilities')
        batch_op.drop_column('book_value_per_share')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_value_per_share', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_liabilities', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('operating_cash_flow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('shares_outstanding')
        batch_op.drop_column('cash_and_equivalents')
        batch_op.drop_column('total_borrowings')

    # ### end Alembic commands ###
